### ISSUE TITLE
Error: Failed to set Next.js data cache

### ISSUE THREAD

**Issue by davidmytton** [arcjet/arcjet-js#836]
I have seen one instance of this error with Next.js and had a report from a user about it as well, but I can't reproduce. It logs a huge base64 encoded string and then errors:

```
...
Q0AAGFhAAACAAAABQAAAAAAAAD+DQAAbm4AAAIAAAAFAAAAAAAAAP8NAABpaQAAAgAAAAUAAAAAAAAAJQ4AAGVlAAACAAAABQAAAAAAAAABDgAAc3MAAAIAAAAFAAAAAAAAAAIOAAB1dQAAAgAAAAUAAAAAAAAAAw4AAHBwAAACAAAABQAAAAAAAAAEDgAAZWUAAAIAAAAFAAAAAAAAAAUOAABycgAAAgAAAAUAAAAAAAAABg4AAGZmAAACAAAABQAAAAAAAAAHDgAAZWUAAAIAAAAFAAAAAAAAAAgOAABlZQAAAgAAAAUAAAAAAAAACQ4AAGRkAAACAAAABQAAAAAAAAAlDgAAcnIAAAIAAAAFAAAAAAAAAAsOAAB3dwAAAgAAAAUAAAAAAAAADA4AADMzAAACAAAABQAAAAAAAAANDgAAY2MAAAIAAAAFAAAAAAAAAA4OAABfXwAAAgAAAAUAAAAAAAAADw4AAHV1AAACAAAABQAAAAAAAAAQDgAAbm4AAAIAAAAFAAAAAAAAABEOAABpaQAAAgAAAAUAAAAAAAAAEg4AAGNjAAACAAAABQAAAAAAAAATDgAAb28AAAIAAAAFAAAAAAAAABQOAABycgAAAgAAAAUAAAAAAAAAJQ4AAG5uAAACAAAABQAAAAAAAAAWDgAAZGQAAAIAAAAFAAAAAAAAABcOAABvbwAAAgAAAAUAAAAAAAAAGA4AAG1tAAACAAAABQAAAAAAAAAZDgAAYWEAAAIAAAAFAAAAAAAAABoOAABpaQAAAgAAAAUAAAAAAAAAGw4AAG5uAAACAAAABQAAAAAAAAAcDgAAc3MAAAIAAAAFAAAAAAAAAB0OAAAgIAAAAgAAAAUAAAAAAAAAHg4AAHBwAAACAAAABQAAAAAAAAAfDgAAcnIAAAIAAAAFAAAAAAAAACAOAABvbwAAAgAAAAUAAAAAAAAAIQ4AAGpqAAACAAAABQAAAAAAAAAiDgAAZWUAAAIAAAAFAAAAAAAAACMOAABjYwAAAgAAAAUAAAAAAAAAJA4AAHR0AAACAAAABQAAAAAAAAAlDgAALy8AAAIAAAAFAAAABgAAACYOAEGMlYMBCwUBAAAACABBoJWDAQsBAQBBnN+DAQsDQRABAEHc/4cBCwEoAEcJcHJvZHVjZXJzAQxwcm9jZXNzZWQtYnkCDXdpdC1jb21wb25lbnQHMC4yMDEuMBB3aXQtYmluZGdlbi1ydXN0BjAuMjIuMA== Error: Failed to set Next.js data cache, items over 2MB can not be cached (4498890 bytes)
example-next:dev:     at IncrementalCache.set (/app/node_modules/next/dist/server/lib/incremental-cache/index.js:391:23)
example-next:dev:     at /app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:51077
example-next:dev:     at async wasm (webpack-internal:///(rsc)/../../node_modules/@arcjet/analyze/_virtual/arcjet_analyze_js_req.component.core.js:39:22)
example-next:dev:     at async moduleFromPath (webpack-internal:///(rsc)/../../node_modules/@arcjet/analyze/index.js:23:25)
example-next:dev:     at async Promise.all (index 0)
example-next:dev: ✦Aj [analyze wasm] generate_fingerprint input: 192.168.247.0
example-next:dev: ✦Aj [analyze wasm] Struct = Fingerprint { prefix: "fp", version: 1, ip: 192.168.247.0 }
example-next:dev: ✦Aj [analyze wasm] String = 192.168.247.0
example-next:dev: ✦Aj fingerprint (node): fp_1_918a34e3c2a0124ba9d2f7ba2d862b60e6f6bff2d4a428e8b99b6235aa0d0d26
example-next:dev: ✦Aj Latency fingerprint: 209.831ms
example-next:dev: ✦Aj Latency cache: 0.027ms
example-next:dev: ✦Aj Latency local: 209.96ms
example-next:dev: ✦Aj Decide request to https://decide.arcjet.orb.local:4082
example-next:dev: ✦Aj Decide response {
example-next:dev:   id: 'req_01hyz6j5qheqq8x3331962r1pk',
example-next:dev:   fingerprint: 'fp_1_918a34e3c2a0124ba9d2f7ba2d862b60e6f6bff2d4a428e8b99b6235aa0d0d26',
example-next:dev:   path: '/api_app/protect_api',
example-next:dev:   runtime: 'node',
example-next:dev:   ttl: 0,
example-next:dev:   conclusion: 'ALLOW',
example-next:dev:   reason: ArcjetShieldReason { type: 'SHIELD', shieldTriggered: false },
example-next:dev:   ruleResults: [
example-next:dev:     ArcjetRuleResult {
example-next:dev:       ruleId: '',
example-next:dev:       ttl: 0,
example-next:dev:       state: 'RUN',
example-next:dev:       conclusion: 'ALLOW',
example-next:dev:       reason: [ArcjetShieldReason]
example-next:dev:     }
example-next:dev:   ]
example-next:dev: }
example-next:dev: ✦Aj Latency decideApi: 18.351ms
example-next:dev: ✦Aj Latency remote: 18.391ms
example-next:dev:  GET /api_app/protect_api 200 in 894ms
```

**Comment by davidmytton** [comment]
For Next.js this [can be controlled by setting](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#individual-fetch-requests) `{ cache: 'no-store' }` on `fetch` (which [will be the default from Next.js 15](https://nextjs.org/blog/next-15-rc#caching-updates)).

**Comment by davidmytton** [comment]
I was able to reproduce on the Next.js app router with one of our test routes: https://example-next.arcjet.orb.local/api_app/protect_api_rl. It doesn't reproduce with the pages router. Adding `const dynamic = 'force-dynamic'` fixes the issue because it opts the route out of caching.

**Comment by blaine-arcjet** [comment]
I followed the reproduction and added `{ cache: 'no-store' }` to the `fetch` and it no longer errors. I'll get a patch submitted shortly.
